src/Ultranet/CoreBundle/Entity/ImageFormation.php
<?php

namespace Ultranet\CoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Image
 *
 * @ORM\Table(name="ultranet_image_formation")
 * @ORM\Entity(repositoryClass="Ultranet\CoreBundle\Repository\ImageFormationRepository")
 * @Vich\Uploadable
 */
class ImageFormation
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;

    /**
     * @Vich\UploadableField(mapping="image_formation", fileNameProperty="imageName")
     * @Assert\Image()
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(name="image_name", type="string", length=255)
     *
     * @var string
     */
    private $imageName;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set imageName
     *
     * @param string $imageName
     *
     * @return ImageFormation
     */
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;

        return $this;
    }

    /**
     * Get imageName
     *
     * @return string
     */
    public function getImageName()
    {
        return $this->imageName;
    }

    /**
     * @return File
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param File $imageFile
     * @return $this
     */
    public function setImageFile(File $imageFile)
    {
        $this->imageFile = $imageFile;

        if ($imageFile){
            $this->createdAt = new \DateTime('now');
        }

        return $this;
    }



    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return ImageFormation
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @return string
     */
    public function getWebPath() {
        return 'uploads/images/formations/'.$this->getImageName();
    }
}

src/Ultranet/CoreBundle/Controller/CoreController.php
<?php

namespace Ultranet\CoreBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class CoreController extends Controller
{
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $formationRep = $em->getRepository('UltranetCoreBundle:Formation');
        $formations = $formationRep->findBy(array(), null, 6);
        return $this->render('UltranetCoreBundle:Core:index.html.twig', array('formations' => $formations));
    }
}

src/Ultranet/CoreBundle/Resources/views/Core/index.html.twig
{% extends 'UltranetCoreBundle::layout.html.twig' %}
{% block title %}
    Accueil - {{ parent() }}
{% endblock %}
{% block body_content %}
    {% include 'UltranetCoreBundle:Includes:banner.html.twig' %}
    <div width="100%" id="content-body">
        <div class="container">
            <!-- Marketing Icons Section -->
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <h1 class="page-header">
                        Nos formations
                        <small>populaires</small>
                    </h1>
                </div>
            </div>
            <div class="row formation">
                {% if formations is not empty %}
                    {% for formation in formations %}
                        <div class="col-md-4">
                            <div class="card">
                                {% if formation.image is not null %}
                                    <img class="card-img-top" src="{{ asset(formation.image.webPath) }}"
                                         alt="image formation">
                                {% else %}
                                    <img class="card-img-top"
                                         src="{{ asset('uploads/images/formations/formation_default.jpg') }}"
                                         alt="image formation">
                                {% endif %}
                                <div class="card-block">
                                    <h4 class="card-title">{{ formation.name | truncate(30) }}</h4>
                                    <p class="card-text">
                                        {{ formation.description | truncate(90) }}
                                    </p>
                                    <a href=" {{ path('ultranet_core_show_formationpage', {'slug' : formation.slug}) }} "
                                       class="btn btn-success">Lire plus ...</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <!-- /.row -->

            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <h1 class="page-header">
                        Pourquoi choisir Ultranet ?
                    </h1>
                </div>
                <div class="col-md-4">
                    <div class="why">
                        <i class="fa fa-book fa-5x"></i>
                        <span class="why-desc">
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis
                        </span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="why">
                        <i class="fa fa-umbrella fa-5x"></i>
                        <span class="why-desc">
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis
                        </span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="why">
                        <i class="fa fa-flag fa-5x"></i>
                        <span class="why-desc">
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, optio corporis
                        </span>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}