src/Ultranet/ForumBundle/Entity/Forum.php
<?php

namespace Ultranet\ForumBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Forum
 *
 * @ORM\Table(name="ultranet_forum")
 * @ORM\Entity(repositoryClass="Ultranet\ForumBundle\Repository\ForumRepository")
 */
class Forum {

  /**
   * @var int
   *
   * @ORM\Column(name="id", type="integer")
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  private $id;

  /**
   * @var string
   *
   * @ORM\Column(name="name", type="string", length=255, unique=true)
   */
  private $name;

  /**
   * @var string
   *
   * @ORM\Column(name="description", type="text", nullable=true)
   */
  private $description;

  /**
   * @var int
   *
   * @ORM\Column(name="ordre", type="integer")
   */
  private $ordre;

  /**
   * @ORM\ManyToOne(targetEntity="Category")
   */
  private $category;

  /**
   * @ORM\OneToOne(targetEntity="Post")
   */
  private $lastPost;

  /**
   * @ORM\OneToMany(targetEntity="Topic", mappedBy="forum")
   */
  private $topics;

  /**
   * Constructor
   */
  public function __construct() {
    $this->topics = new \Doctrine\Common\Collections\ArrayCollection();
  }

  /**
   * Get id
   *
   * @return int
   */
  public function getId() {
    return $this->id;
  }

  /**
   * Set name
   *
   * @param string $name
   *
   * @return Forum
   */
  public function setName($name) {
    $this->name = $name;

    return $this;
  }

  /**
   * Get name
   *
   * @return string
   */
  public function getName() {
    return $this->name;
  }

  /**
   * Set description
   *
   * @param string $description
   *
   * @return Forum
   */
  public function setDescription($description) {
    $this->description = $description;

    return $this;
  }

  /**
   * Get description
   *
   * @return string
   */
  public function getDescription() {
    return $this->description;
  }

  /**
   * Set ordre
   *
   * @param integer $ordre
   *
   * @return Forum
   */
  public function setOrdre($ordre) {
    $this->ordre = $ordre;

    return $this;
  }

  /**
   * Get ordre
   *
   * @return int
   */
  public function getOrdre() {
    return $this->ordre;
  }

  /**
   * Set category
   *
   * @param \Ultranet\ForumBundle\Entity\Category $category
   *
   * @return Forum
   */
  public function setCategory(\Ultranet\ForumBundle\Entity\Category $category = null) {
    $this->category = $category;

    return $this;
  }

  /**
   * Get category
   *
   * @return \Ultranet\ForumBundle\Entity\Category
   */
  public function getCategory() {
    return $this->category;
  }

  /**
   * Set lastPost
   *
   * @param \Ultranet\ForumBundle\Entity\Post $lastPost
   *
   * @return Forum
   */
  public function setLastPost(\Ultranet\ForumBundle\Entity\Post $lastPost = null) {
    $this->lastPost = $lastPost;

    return $this;
  }

  /**
   * Get lastPost
   *
   * @return \Ultranet\ForumBundle\Entity\Post
   */
  public function getLastPost() {
    return $this->lastPost;
  }

  /**
   * Add topic
   *
   * @param \Ultranet\ForumBundle\Entity\Topic $topic
   *
   * @return Forum
   */
  public function addTopic(\Ultranet\ForumBundle\Entity\Topic $topic) {
    $this->topics[] = $topic;

    return $this;
  }

  /**
   * Remove topic
   *
   * @param \Ultranet\ForumBundle\Entity\Topic $topic
   */
  public function removeTopic(\Ultranet\ForumBundle\Entity\Topic $topic) {
    $this->topics->removeElement($topic);
  }

  /**
   * Get topics
   *
   * @return \Doctrine\Common\Collections\Collection
   */
  public function getTopics() {
    return $this->topics;
  }
  
  /**
   * Methode permettant d'evaluer la nombre de posts sur le forum
   * @return type
   */
  public function getNombrePosts() {
    $nb = 0;
    
    foreach ($this->topics as $topic) {
      $nb += count($topic->getPosts()->toArray());
    }
    
    return $nb;
  }

}

src/Ultranet/ForumBundle/Controller/ForumController.php
<?php

namespace Ultranet\ForumBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Ultranet\ForumBundle\Entity\Forum;

class ForumController extends Controller
{
  /**
   *
   * @return type
   */
  public function indexAction()
  {
    $em = $this->getDoctrine()->getManager();

    $repForum = $em->getRepository('UltranetForumBundle:Forum');
    $repCategorie = $em->getRepository('UltranetForumBundle:Category');

    $forums = $repForum->findAll();
    $categories = $repCategorie->findAll();

    return $this->render('UltranetForumBundle:Forum:index.html.twig', array(
      'forums' => $forums,
      'categories' => $categories
    ));
  }

  /**
   * @param Request $request
   * @return \Symfony\Component\HttpFoundation\Response
   */
  public function searchAction(Request $request)
  {
    $searchPattern = '';
    $resultats     = array();

    $rep = $this
            ->getDoctrine()
            ->getManager()
            ->getRepository('UltranetForumBundle:Topic');

    if ($request->get("search_pattern")) {
      $searchPattern = $request->get("search_pattern");
      $resultats = $rep->findLike($searchPattern);
    }

    return $this->render('UltranetForumBundle:Forum:results.html.twig', array(
      'resultats'     => $resultats,
      'searchPattern' => $searchPattern
    ));
  }
}

src/Ultranet/ForumBundle/Resources/views/Forum/index.html.twig
{% extends "UltranetForumBundle::layout.html.twig" %}

{% block title %}
  Forum - {{ parent() }}
{% endblock %}


{% block forum_content %}
  <div class="row">
    <div class="col-md-12">

      {% for categorie in categories %}
        <div class="panel panel-success forum-list">
          <div class="panel-heading cursor-pointer">
            <i class="fa fa-comment-o"></i> {{ categorie.nom }}
            <span class="pull-right"><i class="fa fa-expand"></i></span>
            <h4 class="text">Veuillez vous exprimer ici en posant dans le forum approprié votre problème.</h4>
          </div>
          <div class="panel-body">



            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th style="width: 650px">Nom du forum</th>
                  <th style="width: 100px">Sujets</th>
                  <th style="width: 100px">Posts</th>
                  <th style="width: 350px">Dernier post</th>
                </tr>
              </thead>
              <tbody>

                {% for forum in forums %}

                  {% if forum.category.nom==categorie.nom %}
                    <tr>
                      <td>
                        <div class="row">
                          <div class="col-md-1">
                            <i class="fa fa-comments-o fa-2x"></i>
                          </div>
                          <div class="col-md-11">
                            <h4>
                              <a href="{{ path('ultranet_forum_topics', {'forum_name': forum.name, 'page': 1}) }}">{{ forum.name }}</a>
                            </h4>
                            <p>{{ forum.description }}</p>
                          </div>
                        </div>
                      </td>
                      <td><span class="badge">{{ forum.topics|length }}</span></td>
                      <td><span class="badge">{{ forum.nombrePosts }}</span></td>
                      <td>
                        {% if forum.lastPost is not null %}
                          <p>
                            Par <b>{{ forum.lastPost.createur.username }}</b> <br>
                            {{ forum.lastPost.texte }} <br>
                            Le <b><em>{{ forum.lastPost.postTime|date('d/m/y') }}</em></b>
                          </p>
                        {% endif %}
                      </td>
                    </tr>
                  {% endif %}

                {% endfor %}

              </tbody>
            </table>

          </div>
        </div>

      {% endfor %}

    </div>
  </div>
{% endblock %}

src/Ultranet/ForumBundle/Resources/views/Forum/results.html.twig
{% extends "UltranetForumBundle::layout.html.twig" %}

{% block title %}
  Résultats de la recherche - {{ parent() }}
{% endblock %}

{% block forum_content %}

  <h1>Résultats pour <small>{{ searchPattern }}</small></h1>

  {% for resultat in resultats %}
    <div class="panel panel-default">
      <div class="panel-body">
        {{ resultat.title }}
      </div>
    </div>
  {% endfor %}

{% endblock %}